### ISSUE TITLE
IDE depends on JavaFX, not included in jar

### ISSUE THREAD

**Issue by pandeiro** [ui4j/ui4j#20]
Following the instructions for running the ui4j IDE on the README --

```
java -jar ui4j-ide-1.1.0.jar
```

-- produces the following Exception (with stacktrace):

```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/scene/Parent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
	at java.lang.Class.getMethod0(Class.java:3010)
	at java.lang.Class.getMethod(Class.java:1776)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: javafx.scene.Parent
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

Is this expected? If the class mentioned is not supposed to be included in the IDE jar, how is one supposed to obtain and include it? Could that information be added to the README?

**Comment by ui4j** [comment]
Could you please check your Java version.

Here is my Java version:

java version **"1.8.0_31"**
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) Client VM (build 25.31-b07, mixed mode)

Ui4j requires Java 8, Java 7 is not supported.

**Comment by ui4j** [comment]
Unfortunately i am not going to support & develop the ide module for the new versions.
