### ISSUE TITLE
Samples throw IllegalStateException under Windows

### ISSUE THREAD

**Issue by mwberry** [ui4j/ui4j#23]
When running any of the sames containing `page.waitUntilDocReady();` on Windows, a stack trace is generated indicating that the thread executing the call is not the JavaFX thread and therefore cannot make this call.

OS: Windows 7 x64
JVM: Oracle Java 8.0.20.26
IDE: Idea IntelliJ 14.1.1
Sample: CnnTechNews.java
Stacktrace:
```
Exception in thread "main" java.lang.IllegalStateException: Not on FX application thread; currentThread = main
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:210)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:393)
	at javafx.scene.web.WebEngine.checkThread(WebEngine.java:1170)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:932)
	at com.ui4j.webkit.spi.WebKitJavaScriptEngine.executeScript(WebKitJavaScriptEngine.java:22)
	at com.ui4j.webkit.browser.WebKitPage.waitUntilDocReady(WebKitPage.java:225)
	at com.ui4j.webkit.browser.WebKitPage.waitUntilDocReady(WebKitPage.java:220)
	at com.ui4j.sample.CnnTechNews.main(CnnTechNews.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Same setup, but executing without the IDE:
```
Exception in thread "main" java.lang.IllegalStateException: Not on FX application thread; currentThread = main
        at com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
        at javafx.scene.web.WebEngine.checkThread(Unknown Source)
        at javafx.scene.web.WebEngine.executeScript(Unknown Source)
        at com.ui4j.webkit.spi.WebKitJavaScriptEngine.executeScript(WebKitJavaScriptEngine.java:22)
        at com.ui4j.webkit.browser.WebKitPage.waitUntilDocReady(WebKitPage.java:225)
        at com.ui4j.webkit.browser.WebKitPage.waitUntilDocReady(WebKitPage.java:220)
        at com.ui4j.sample.CnnTechNews.main(CnnTechNews.java:29)
```

**Comment by ui4j** [comment]
page.waitUntilDocReady() method removed. Ui4j waits automatically until document is ready to use.
