### ISSUE TITLE
Samples cause NullPointerException under Ubuntu 14.04

### ISSUE THREAD

**Issue by mwberry** [ui4j/ui4j#24]
When running any of the samples under Ubuntu 14.04, a number of stack traces are generated indicating that there was a NullPointerException in ` com.sun.javafx.Utils.getScreen()`

OS: Ubuntu 14.04
JVM: Oracle Java 8.0.40.25
Sample: CnnTechNews.java
Stacktrace:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.sun.javafx.Utils.getScreen(Utils.java:686)
        at com.sun.javafx.webkit.WebPageClientImpl.getScreenBounds(WebPageClientImpl.java:105)
        at com.sun.webkit.WCWidget.fwkGetScreenRect(WCWidget.java:118)
        at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
        at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
        at com.sun.webkit.Timer.notifyTick(Timer.java:64)
        at javafx.scene.web.WebEngine$PulseTimer.lambda$static$45(WebEngine.java:1167)
        at javafx.scene.web.WebEngine$PulseTimer$$Lambda$77/1085514134.pulse(Unknown Source)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:314)
        at com.sun.javafx.tk.Toolkit$$Lambda$109/663746818.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:313)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:340)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:525)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:505)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$400(QuantumToolkit.java:334)
        at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$47/662647378.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
        at com.sun.glass.ui.gtk.GtkApplication$$Lambda$43/2109720668.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
```

This stack trace appears several dozen times, then the last stack trace appears to be the same one from https://github.com/ui4j/ui4j/issues/23

```
Exception in thread "main" java.lang.IllegalStateException: Not on FX application thread; currentThread = main
        at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:204)
        at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:438)
        at javafx.scene.web.WebEngine.checkThread(WebEngine.java:1182)
        at javafx.scene.web.WebEngine.executeScript(WebEngine.java:946)
        at com.ui4j.webkit.spi.WebKitJavaScriptEngine.executeScript(WebKitJavaScriptEngine.java:22)
        at com.ui4j.webkit.browser.WebKitPage.waitUntilDocReady(WebKitPage.java:225)
        at com.ui4j.webkit.browser.WebKitPage.waitUntilDocReady(WebKitPage.java:220)
        at com.ui4j.sample.CnnTechNews.main(CnnTechNews.java:29)
```

**Comment by mwberry** [comment]
This appears to be due to a bug in JavaFX. The bug occurs when a WebView is not associated with a scene. Based on my understanding of the WebKitPage code, this association does not happen until page.show() is called. Therefore there is a race condition. If the time interval between calling browser.navigate() and page.show() exceeds the time it takes for the JavaFx thread to pulse, then this NPE will be thrown.

**Comment by micheljung** [comment]
Did you open a bug report on this? I commented on this one: https://javafx-jira.kenai.com/browse/RT-39562

**Comment by ui4j** [comment]
No, i didnt open bug report to javafx-jira. Thanks for the comment, i am watching the [issue](https://javafx-jira.kenai.com/browse/RT-39562).

**Comment by mwberry** [comment]
Opened https://javafx-jira.kenai.com/browse/RT-40639 but it was resolved since it utilized non-public interfaces in the simplified repro code. It does link to two other issues which are both marked Fixed but look very similar in nature to this stack trace.

**Comment by ui4j** [comment]
`WebView` is associated with the `Stage` & `Scene` after the page load if and only if `Page.show()` is called. I changed the implementation and `Stage` & `Scene` created always initialized before the page load. The new implementation seems work properly with `CnnTechNews.java` sample for Windows 8.1. Could you please test the current branch for your test case?

Thanks
