### ISSUE TITLE
ClassCastException on toString and others

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#30]
I have written a simple html page to test ui4j. This is the code:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Fancy Title</title>
  </head>
  <body>
    <h1>Header 1</h1>
    <ul>
      <li>a</li>
      <li>b</li>
    </ul>
  </body>
</html>
```

I simply call query( "ul" ).getChildren() and do a toString on the children. First of all I get 5 children. The ul clearly has only 2 children. As soon as I call toString a ClassCastException will be thrown:

```
Exception in thread "JavaFX Application Thread" com.ui4j.api.util.Ui4jException: com.ui4j.api.util.Ui4jException: com.ui4j.api.util.Ui4jException: java.lang.ClassCastException: com.sun.webkit.dom.TextImpl cannot be cast to com.sun.webkit.dom.HTMLElementImpl
	at com.ui4j.webkit.proxy.WebKitProxy$CallableExecutor.run(WebKitProxy.java:46)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
	at com.sun.javafx.application.PlatformImpl$$Lambda$50/1078027894.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl$$Lambda$49/2058497414.run(Unknown Source)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:77)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:47)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.ui4j.api.util.Ui4jException: com.ui4j.api.util.Ui4jException: java.lang.ClassCastException: com.sun.webkit.dom.TextImpl cannot be cast to com.sun.webkit.dom.HTMLElementImpl
	at com.ui4j.webkit.proxy.WebKitProxy$WebKitInterceptor.execute(WebKitProxy.java:93)
	at com.ui4j.webkit.dom.WebKitElement$ByteBuddy$q1B71w3r.getInnerHTML(Unknown Source)
	at com.ui4j.webkit.dom.WebKitElement.toString(WebKitElement.java:891)
	at com.ui4j.webkit.dom.WebKitElement$ByteBuddy$q1B71w3r.toString$accessor$Ap3M9OOt(Unknown Source)
	at com.ui4j.webkit.dom.WebKitElement$ByteBuddy$q1B71w3r$accessor$apqrvbTv.call(Unknown Source)
	at com.ui4j.webkit.proxy.WebKitProxy$CallableExecutor.run(WebKitProxy.java:44)
	... 8 more
Caused by: com.ui4j.api.util.Ui4jException: java.lang.ClassCastException: com.sun.webkit.dom.TextImpl cannot be cast to com.sun.webkit.dom.HTMLElementImpl
	at com.ui4j.webkit.proxy.WebKitProxy$WebKitInterceptor.execute(WebKitProxy.java:93)
	at com.ui4j.webkit.dom.WebKitElement$ByteBuddy$q1B71w3r.getHtmlElement(Unknown Source)
	at com.ui4j.webkit.dom.WebKitElement.getInnerHTML(WebKitElement.java:475)
	at com.ui4j.webkit.dom.WebKitElement$ByteBuddy$q1B71w3r.getInnerHTML$accessor$GRwOi7c8(Unknown Source)
	at com.ui4j.webkit.dom.WebKitElement$ByteBuddy$q1B71w3r$accessor$mZd7SM7v.call(Unknown Source)
	at com.ui4j.webkit.proxy.WebKitProxy$WebKitInterceptor.execute(WebKitProxy.java:91)
	... 13 more
Caused by: java.lang.ClassCastException: com.sun.webkit.dom.TextImpl cannot be cast to com.sun.webkit.dom.HTMLElementImpl
	at com.ui4j.webkit.dom.WebKitElement.getHtmlElement(WebKitElement.java:658)
	at com.ui4j.webkit.dom.WebKitElement$ByteBuddy$q1B71w3r.getHtmlElement$accessor$nTBZOnoC(Unknown Source)
	at com.ui4j.webkit.dom.WebKitElement$ByteBuddy$q1B71w3r$accessor$h3vC2uVl.call(Unknown Source)
	at com.ui4j.webkit.proxy.WebKitProxy$WebKitInterceptor.execute(WebKitProxy.java:91)
	... 18 more
```

**Comment by hstaudacher** [comment]
Currently I need to filter the children with 

```
children.stream().filter( raw -> ( ( WebKitElement )raw ).getNode() instanceof HTMLElement )
```

**Comment by ui4j** [comment]
Thanks for the bug report.
ui4j couldnt cast TextImpl to HTMLElementImpl because of getChildren doesn't filter text nodes.
New getChildren implementation filters text nodes and it works for the sample test.

**Comment by hstaudacher** [comment]
That was quick ;)
