### ISSUE TITLE
NPE in WorkerLoadListener

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#50]
After adding an `Interceptor`:

```java
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.ui4j.webkit.WebKitBrowser$WorkerLoadListener.changed(WebKitBrowser.java:210)
	at com.ui4j.webkit.WebKitBrowser$WorkerLoadListener.changed(WebKitBrowser.java:182)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:145)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1226)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1337)
	at javafx.scene.web.WebEngine$LoadWorker.access$1100(WebEngine.java:1219)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1206)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2387)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2231)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:819)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$92(URLLoader.java:810)
	at com.sun.webkit.network.URLLoader$$Lambda$106/1843014486.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
	at com.sun.javafx.application.PlatformImpl$$Lambda$55/452476773.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl$$Lambda$54/1496889919.run(Unknown Source)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:77)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:47)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ui4j** [comment]
Thanks for the bug report. NullPointerException occurs if the location is loaded from local drive.
