### ISSUE TITLE
Can't access client side cookies 

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#55]
The `Interceptor` mechanism works create to access cookies that were set by the server. But you have no chance to access cookies that are set by the client e.g. via JavaScript.

Example html:

```html
<!DOCTYPE html>
<html>
  <head>
  <title>Session Test</title>
  </head>
  <body>
    
    <ul id="cookies"></ul>
    
    <script src="js/jquery-2.1.4.min.js" type="text/javascript"></script>
    <script type="text/javascript">
      
      var pairs = document.cookie.split( ";" );
      for( var i = 0; i < pairs.length; i++ ) {
        if( pairs[ i ] !== "" ) {
          var pair = pairs[ i ].split( "=" );
          $( "#cookies" ).append( "<li>" + pair[ 0 ] + "=" + unescape( pair[1] ) );
        }
      }
      
      function createCookie(name, value, days) {
          var expires;

          if (days) {
              var date = new Date();
              date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
              expires = "; expires=" + date.toGMTString();
          } else {
              expires = "";
          }
          document.cookie = encodeURIComponent(name) + "=" + encodeURIComponent(value) + expires + "; path=/";
      }
      
      function guid() {
        function s4() {
          return Math.floor((1 + Math.random()) * 0x10000)
            .toString(16)
            .substring(1);
        }
        return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
          s4() + '-' + s4() + s4() + s4();
      }

      function readCookie(name) {
          var nameEQ = encodeURIComponent(name) + "=";
          var ca = document.cookie.split(';');
          for (var i = 0; i < ca.length; i++) {
              var c = ca[i];
              while (c.charAt(0) === ' ') c = c.substring(1, c.length);
              if (c.indexOf(nameEQ) === 0) return decodeURIComponent(c.substring(nameEQ.length, c.length));
          }
          return null;
      }
      
      if( readCookie( "foobar" ) == null ) {
        createCookie( "foobar", guid(), 1 );
      }
      
    </script>
    
  </body>
</html>
```
The is no way to access the cookie "foobar" via UI4J API.

**Comment by ui4j** [comment]
You could use Page.executeScript to read client side cookies. [This](https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/test/java/com/ui4j/test/ClientSideCookieTest.java) unit test might be used as a reference point.

**Comment by hstaudacher** [comment]
Thanks, any chance this makes it to the `Page`?

**Comment by hstaudacher** [comment]
I can't get it to work. `String cookie = (String) page.executeScript("document.cookie");` always returns null in my case. I'm using the html posted above and tested it with two web servers.

**Comment by hstaudacher** [comment]
I modified the html a little bit to always set the `foobar` cookie and show it in a list. Open it with any browser does show the foobar cookie in the list. But when running it with UI4J no cookie is shown. I disabled headless mode to see what is rendered.

```html
<!DOCTYPE html>
<html>
  <head>
  <title>Session Test</title>
  </head>
  <body>
  
    <div id="user-agent"></div>
    
    <ul id="cookies"></ul>
    
    
    <script src="js/jquery-2.1.4.min.js" type="text/javascript"></script>
    <script type="text/javascript">
      $( "#user-agent" ).text( navigator.userAgent );
      
      function createCookie(name, value, days) {
          var expires;

          if (days) {
              var date = new Date();
              date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
              expires = "; expires=" + date.toGMTString();
          } else {
              expires = "";
          }
          document.cookie = encodeURIComponent(name) + "=" + encodeURIComponent(value) + expires + "; path=/";
      }
      
      function guid() {
        function s4() {
          return Math.floor((1 + Math.random()) * 0x10000)
            .toString(16)
            .substring(1);
        }
        return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
          s4() + '-' + s4() + s4() + s4();
      }

      function readCookie(name) {
          var nameEQ = encodeURIComponent(name) + "=";
          var ca = document.cookie.split(';');
          for (var i = 0; i < ca.length; i++) {
              var c = ca[i];
              while (c.charAt(0) === ' ') c = c.substring(1, c.length);
              if (c.indexOf(nameEQ) === 0) return decodeURIComponent(c.substring(nameEQ.length, c.length));
          }
          return null;
      }
      
      if( readCookie( "foobar" ) == null ) {
        createCookie( "foobar", guid(), 1 );
      }
      
      var pairs = document.cookie.split( ";" );
      for( var i = 0; i < pairs.length; i++ ) {
        if( pairs[ i ] !== "" ) {
          var pair = pairs[ i ].split( "=" );
          $( "#cookies" ).append( "<li>" + pair[ 0 ] + "=" + unescape( pair[1] ) );
        }
      }
      
    </script>
    
  </body>
</html>
```

**Comment by ui4j** [comment]
This might be environmental problem. The [test](https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/test/java/com/ui4j/test/ClientSideCookieTest.java) works for my local development environment (Windows 8.1). Fails for the drone.io (Ubuntu 14.04) but works for another ubuntu 14.04 instance which is hosted at the digitalocean.

Could you please let me know your test environment? Java, 32-64bit, OS etc.

**Comment by hstaudacher** [comment]
OSX

```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

When running `mvn clean install` for UI4J all tests are passing.

**Comment by ui4j** [comment]
Two major bugs fixed. One of them is NullPointerException and the other one is [Localization](https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/main/java/com/ui4j/webkit/spi/WebKitJavaScriptEngine.java#L31) issue. I am still not to sure about to use `Locale.ENGLISH` to parse numeric values. Maybe i shouldnt do type conversion and take responsibility.

**Comment by hstaudacher** [comment]
With the latest version I'm getting this exception

```java
Exception in thread "JavaFX Application Thread" com.ui4j.api.util.Ui4jException: netscape.javascript.JSException: Error: SecurityError: DOM Exception 18
	at com.ui4j.webkit.proxy.WebKitProxy$CallableExecutor.run(WebKitProxy.java:48)
	at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:301)
	at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:298)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl$6.run(PlatformImpl.java:298)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:77)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:47)
	at java.lang.Thread.run(Thread.java:745)
Caused by: netscape.javascript.JSException: Error: SecurityError: DOM Exception 18
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1410)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:934)
	at com.ui4j.webkit.spi.WebKitJavaScriptEngine.executeScript(WebKitJavaScriptEngine.java:26)
	at com.ui4j.webkit.browser.WebKitPage.executeScript(WebKitPage.java:231)
	at com.ui4j.webkit.browser.WebKitPage$ByteBuddy$Mw20d5vN.executeScript$accessor$TXJsuC0z(Unknown Source)
	at com.ui4j.webkit.browser.WebKitPage$ByteBuddy$Mw20d5vN$auxiliary$RsUWhf6Q.call(Unknown Source)
	at com.ui4j.webkit.proxy.WebKitProxy$CallableExecutor.run(WebKitProxy.java:46)
```

**Comment by ui4j** [comment]
DOM Exception 18

```
This excep­tion is thrown when your code is try­ing to access some­thing it shouldn’t, includ­ing cross-domain resources or stuff on your local filesystem.
```

or

```
You're most likely using this on a local file over the file:// URI scheme, which cannot have cookies set. Put it on a local server so you can use http://localhost.
```

http://stackoverflow.com/questions/2704929/uncaught-error-security-err-dom-exception-18-when-i-try-to-set-a-cookie

Please make sure that you arent trying to read cookie from local file.

**Comment by hstaudacher** [comment]
Damn it. My local server was shut down. Strange that this exception is thrown in the case of a non responding server. 

Anyway, still not getting the cookies.

**Comment by ui4j** [comment]
Could you please review my latest [commit](https://github.com/ui4j/ui4j/commit/137cc0db53bd5872295cb89be9cf31b88d8983d6). May be i am trying to test the wrong case?

**Comment by hstaudacher** [comment]
It's the right test. But I'm still using your suggestion with `executeScript( "document.cookie" )`

**Comment by ui4j** [comment]
I add an extra assertion to test `executeScript( "document.cookie" )`.

I can reproduce the problem with the Dummy Cookie Handler.

```java
CookieHandler.setDefault(new CookieHandler() {

    @Override
    public void put(URI uri, Map<String, List<String>> responseHeaders)
            throws IOException {
    }
    
    @Override
    public Map<String, List<String>> get(URI uri,
            Map<String, List<String>> requestHeaders) throws IOException {
        return new HashMap<>();
    }
});
```

Could you please set the cookie handler before test start.

`CookieHandler.setDefault(new com.sun.webkit.network.CookieManager());`
or
`CookieHandler.setDefault(new com.ui4j.webkit.WebKitIsolatedCookieHandler());`

**Comment by hstaudacher** [comment]
The WebKitIsolatedCookieHandler was set the whole time.

**Comment by ui4j** [comment]
The problem is server side cookies accessed from URL-Loader thread but client side cookies accessed from JavaFX ui thread. Current WebKitIsolatedCookieHandler is not compatible for the client side cookies. I am going to apply workaround solution for the client side cookies.

**Comment by hstaudacher** [comment]
any progress here?

**Comment by ui4j** [comment]
Unfortunately the problem still exist. WebView try to read client cookie from javafx ui thread but `WebKitIsolatedCookieHandler` is comptable with network thread (URL-Loader). For the ui threadThis means that `WebKitIsolatedCookieHandler`

**Comment by hstaudacher** [comment]
hmm, so why closing it?

**Comment by ui4j** [comment]
Sorry :) its my mistake. i clicked the 'close and comment' instead of 'comment' button.
