### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by rc183** [ui4j/ui4j#61]
Hi,

A lot of time I have this exceptions. Do you know why ? :

Exception in thread "JavaFX Application Thread" com.ui4j.api.util.Ui4jException: java.lang.NullPointerException
	at com.ui4j.webkit.proxy.WebKitProxy$CallableExecutor.run(WebKitProxy.java:48)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$57/1860055891.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$55/533388164.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$45/1573090662.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.ui4j.webkit.browser.WebKitPage.addDocumentListener(WebKitPage.java:159)
	at com.ui4j.webkit.browser.WebKitPage$ByteBuddy$PuVAvVPh.addDocumentListener$accessor$g4MY7bhB(Unknown Source)
	at com.ui4j.webkit.browser.WebKitPage$ByteBuddy$PuVAvVPh$auxiliary$tF730zFV.call(Unknown Source)
	at com.ui4j.webkit.proxy.WebKitProxy$CallableExecutor.run(WebKitProxy.java:46)
	... 10 more
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.ui4j.api.event.DocumentLoadEvent.getDocument(DocumentLoadEvent.java:19)
	at com.ui4j.webkit.browser.WebKitPageContext$GlobalEventCleaner.onLoad(WebKitPageContext.java:90)
	at com.ui4j.webkit.browser.WebKitPage$DocumentDelegationListener.changed(WebKitPage.java:125)
	at com.ui4j.webkit.browser.WebKitPage$DocumentDelegationListener.changed(WebKitPage.java:110)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1226)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1337)
	at javafx.scene.web.WebEngine$LoadWorker.access$1100(WebEngine.java:1219)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1206)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2388)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2232)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:830)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$95(URLLoader.java:821)
	at com.sun.webkit.network.URLLoader$$Lambda$138/1176086721.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$57/1860055891.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$55/533388164.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$45/1573090662.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

Thank you

**Comment by ui4j** [comment]
Could you please specify your ui4j version?

**Comment by rc183** [comment]
Yes. It's the version 2.0.0.

<dependency>
        <groupId>com.ui4j</groupId>
        <artifactId>ui4j-all</artifactId>
        <version>2.0.0-SNAPSHOT</version>
    </dependency>

**Comment by rc183** [comment]
Do you have an idea ?

**Comment by rc183** [comment]
I have always this exception if I run my script in a server with 512mb of RAM. Maybe it can help to find the issue : 

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
at com.ui4j.api.event.DocumentLoadEvent.getDocument(DocumentLoadEvent.java:19)
at com.ui4j.webkit.browser.WebKitPageContext$GlobalEventCleaner.onLoad(WebKitPageContext.java:90)
at com.ui4j.webkit.browser.WebKitPage$DocumentDelegationListener.changed(WebKitPage.java:125)
at com.ui4j.webkit.browser.WebKitPage$DocumentDelegationListener.changed(WebKitPage.java:110)
at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1226)
at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1337)
at javafx.scene.web.WebEngine$LoadWorker.access$1100(WebEngine.java:1219)
at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1206)
at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2388)
at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2232)
at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:830)
at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$95(URLLoader.java:821)
at com.sun.webkit.network.URLLoader$$Lambda$138/1176086721.run(Unknown Source)
at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
at com.sun.javafx.application.PlatformImpl$$Lambda$57/1860055891.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
at com.sun.javafx.application.PlatformImpl$$Lambda$55/533388164.run(Unknown Source)
at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
at com.sun.glass.ui.gtk.GtkApplication$$Lambda$45/1573090662.run(Unknown Source)
at java.lang.Thread.run(Thread.java:745)

**Comment by ui4j** [comment]
Thanks for the error report.
I fixed the NullPointerException, you could checkout and build master branch to use the latest version of ui4j.

**Comment by rc183** [comment]
Thank you for the support !
