### ISSUE TITLE
Exception in thread "JavaFX Application Thread" com.ui4j.api.util.Ui4jException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by rc183** [ui4j/ui4j#62]
Hello,

I have a null pointer exception here :

Exception in thread "JavaFX Application Thread" com.ui4j.api.util.Ui4jException: java.lang.NullPointerException
	at com.ui4j.webkit.proxy.WebKitProxy$CallableExecutor.run(WebKitProxy.java:48)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$58/1598919705.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$56/1645612769.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$46/989026034.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.ui4j.webkit.browser.WebKitPage.addDocumentListener(WebKitPage.java:159)
	at com.ui4j.webkit.browser.WebKitPage$ByteBuddy$rbzZNQXi.addDocumentListener$accessor$xrQN5g0Y(Unknown Source)
	at com.ui4j.webkit.browser.WebKitPage$ByteBuddy$rbzZNQXi$auxiliary$mBjwxL8g.call(Unknown Source)
	at com.ui4j.webkit.proxy.WebKitProxy$CallableExecutor.run(WebKitProxy.java:46)
	... 10 more

Do you have an idea why ?

Thanks

**Comment by Lewik** [comment]
Platform.runLater
http://stackoverflow.com/questions/15304203/nullpointerexception-in-javafx-initialize-method

**Comment by ui4j** [comment]
Hi @rc183 

What is your ui4j version?
