### ISSUE TITLE
BrowserFactory.getJxBrowser throws NullPointerException

### ISSUE THREAD

**Issue by Fraer** [ui4j/ui4j#71]
Hello,

I tried to use the ui4j library in a scala project but unfortunately the with ui4j v2.1.0 BrowserFactory.getJxBrowser returns null.

```
C:\tools\Java\jdk1.8.0_25\bin\java -Didea.launcher.port=7535 -Didea.launcher.bin.path=C:\tools\idea14.1.5\bin -Dfile.encoding=windows-1251 -classpath C:\tools\Java\jdk1.8.0_25\jre\lib\charsets.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\deploy.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\javaws.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\jce.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\jfr.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\jfxswt.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\jsse.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\management-agent.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\plugin.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\resources.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\rt.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\ext\access-bridge-64.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\ext\cldrdata.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\ext\dnsns.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\ext\jaccess.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\ext\jfxrt.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\ext\localedata.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\ext\nashorn.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\ext\sunec.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\ext\sunjce_provider.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\ext\sunmscapi.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\ext\sunpkcs11.jar;C:\tools\Java\jdk1.8.0_25\jre\lib\ext\zipfs.jar;C:\workdir\test-ui\target\scala-2.11\classes;C:\Users\VBodnarchuk\.ivy2\cache\org.scala-lang\scala-library\jars\scala-library-2.11.7.jar;C:\Users\VBodnarchuk\.ivy2\cache\com.ui4j\ui4j-all\jars\ui4j-all-2.1.0.jar;C:\tools\idea14.1.5\lib\idea_rt.jar com.intellij.rt.execution.application.AppMain Main
Exception in thread "main" java.lang.NullPointerException
	at Main$.main(Main.scala:11)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 1
```

The main class:

```
import com.ui4j.api.browser.BrowserFactory
object Main {
  def main(args: Array[String]){
    val browser = BrowserFactory.getJxBrowser
    val page = browser.navigate("http://www.google.com")
    page.show()
  }
}
```

The build.sbt
```
name := "test-ui"

version := "1.0"

scalaVersion := "2.11.7"


libraryDependencies ++= Seq(
  "com.ui4j" % "ui4j-all" % "2.1.0"
)
```

Am i missing something ?

**Comment by ui4j** [comment]
Hi @Fraer ,

This problem seem duplicate of #69 
Could you please try to use that solution.

**Comment by zzfrankz** [comment]
I tried jxbtrowser in other side project, you need to download a temporary license from their site for development, is this case here?

**Comment by zzfrankz** [comment]
I tried a little bit JxBrowser in ui4j, and got BrowserFactory.getJxBrowser returning null as well, no matter I ran it from intelij or mvn command line after mvn install the ui4j, so I suspect it's something else. Also since I am using mac for development and will test it out eventually on linux, I see in ui4j-jxbrowser pom.xml, JxBrowser dependencies only list jxbtrowser, jxbrowser-win and jxbrowser-development, should other platform dependencies be listed as well: jxbrowser-mac and jxbrowser-linux?
