### ISSUE TITLE
how to handle scrolling in headless mode?

### ISSUE THREAD

**Issue by zzfrankz** [ui4j/ui4j#72]
I am using ui4j library to scape a website, and a button click by emolument.click(), I am getting the following exception: 

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException at com.sun.javafx.webkit.theme.ScrollBarThemeImpl.getThumb(ScrollBarThemeImpl.java:400) at com.sun.javafx.webkit.theme.ScrollBarThemeImpl.thumbPosition(ScrollBarThemeImpl.java:284) at com.sun.javafx.webkit.theme.ScrollBarThemeImpl.getThumbPosition(ScrollBarThemeImpl.java:380)

There was a post similar to this, it was solved by page.show(), but since my application is running at headless mode as a background process, I don't have luxury to turn on page.show(), I am wondering if possible: 
1. catch the scroll event, and ignore it, how? 
2. during launching, can I specify the webview reasonable big enough to avoid scrolling? I don't see this option from api.

**Comment by ui4j** [comment]
Hi @zzfrankz 

Did you call the scroll manually with javascript explicitly or emolument.click() scroll the window implicitly?

**Comment by zzfrankz** [comment]
the element.click() scroll the window implicitly.  looks like it didn’t do any harm to the application except it dumped a  lot exceptions in the log. later on, my coworker reverse engineered the script, and removed the scroll part, since it’s implemented by angluarjs, the reverse engineering wasn’t trivial. 

so I was thinking, if there could an interceptor for the engine to ignore the scroll event. 

On Jan 20, 2016, at 1:08 AM, Ozhan Duz <notifications@github.com> wrote:

Hi @zzfrankz <https://github.com/zzfrankz>
Did you call the scroll manually with javascript explicitly or emolument.click() scroll the window implicitly?
