### ISSUE TITLE
Monocle Seems not To Work with Java jdk1.8.0_91

### ISSUE THREAD

**Issue by asevans48** [ui4j/ui4j#86]
I included the monocle dependency and added the command line option and also tried the java api option. However,  Monocle is never found and I cannot seem to use it for headless mode.

I continually receive this error:

Exception in thread "Thread-2" java.lang.IllegalStateException: Monocle headless platform not found
    at com.ui4j.webkit.ApplicationLauncher.initMonocleHeadless(ApplicationLauncher.java:71)
    at com.ui4j.webkit.ApplicationLauncher.launch(ApplicationLauncher.java:50)
    at com.ui4j.webkit.WebKitBrowser$LauncherThread.run(WebKitBrowser.java:148)
Caused by: java.lang.ClassNotFoundException: com.sun.glass.ui.monocle.MonoclePlatformFactory
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at com.ui4j.webkit.ApplicationLauncher.assignMonoclePlatform(ApplicationLauncher.java:87)
    at com.ui4j.webkit.ApplicationLauncher.initMonocleHeadless(ApplicationLauncher.java:67)
    ... 2 more

How do I resolve this? I have even tried command line options for Monocle. The Monocle options I tried were -Dmonocle.platform=headless and -Dglass.platform=Monocle.

**Comment by wimdeblauwe** [comment]
I am getting the same exception using this dependency:

```
        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>openjfx-monocle</artifactId>
            <version>8u76-b04</version>
            <scope>test</scope>
        </dependency>
```

With JDK 1.8.0_92. Any updates or workarounds?

When I use:

```
<dependency>
            <groupId>org.jfxtras</groupId>
            <artifactId>openjfx-monocle</artifactId>
            <version>1.8.0_20</version>
            <scope>test</scope>
        </dependency>
```

Then my tests seem to run fine (on the same JDK). I do get this printed for each test, but it does not seem to interfere with the tests:

```
java.lang.AbstractMethodError: com.sun.glass.ui.View._getNativeFrameBuffer(J)I
       	at com.sun.glass.ui.View.getNativeFrameBuffer(View.java:755)
       	at com.sun.prism.PresentableState.lock(PresentableState.java:273)
       	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:65)
       	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
       	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
       	at java.lang.Thread.run(Thread.java:745)
```

**Comment by marlondu** [comment]
I got same error with jdk_1.8.0_111

**Comment by ui4j** [comment]
Did you try to use latest Monocle version [8u76-b04](https://mvnrepository.com/artifact/org.testfx/openjfx-monocle/8u76-b04)?

**Comment by ui4j** [comment]
Unfortunately the previous maven jar file is broken.

Solution:

Update your ui4j to 2.2.0 (it's published to jitpack instead of maven central)
Download the Monocle from: https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/lib/openjfx-monocle-8u76-b04.jar?raw=true
