### ISSUE TITLE
ClassCastException when using configuration.setAlertHandler(...)

### ISSUE THREAD

**Issue by jpstotz** [ui4j/ui4j#99]
When an alert handler is set I get an `java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List`

```
Exception in thread "JavaFX Application Thread" com.ui4j.api.util.Ui4jException: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.ui4j.webkit.proxy.WebKitProxy$CallableExecutor.run(WebKitProxy.java:48)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.ui4j.spi.NativeEventManager.bind(NativeEventManager.java:27)
	at com.ui4j.webkit.dom.WebKitDocument.bind(WebKitDocument.java:59)
	at com.ui4j.webkit.dom.WebKitDocument$ByteBuddy$xUvmSaEp.bind$accessor$CPyC5c9b(Unknown Source)
	at com.ui4j.webkit.dom.WebKitDocument$ByteBuddy$xUvmSaEp$auxiliary$dyAciKyT.call(Unknown Source)
	at com.ui4j.webkit.proxy.WebKitProxy$CallableExecutor.run(WebKitProxy.java:46)
	... 7 more
```

    PageConfiguration configuration = new PageConfiguration();
    configuration.setAlertHandler(new AlertHandler() {
        @Override
        public void handle(DialogEvent event) {
            System.out.println("Alert: " + event);
        }
    });
    browser.navigate("https://www.google.com", configuration)

**Comment by ui4j** [comment]
Thanks for the bug report.
Could you please test with latest version 2.2.5

**Comment by jpstotz** [comment]
Thanks, now it works. 
Unfortunately in the mean time I had to replace ui4j with selenium and a real web browser as backend as the JavaFX webkit/web browser does not work with the page I want to automate (and hence ui4j, too).
